import { StepNameType } from 'src/store/app'

const basicStepNames = ['start', 'authors'] as Array<StepNameType>
const advancedStepNames = [
    'identifiers',
    'related-resources',
    'abstract',
    'keywords',
    'license',
    'version-specific'
] as Array<StepNameType>
const allStepNames = [...basicStepNames, ...advancedStepNames]

describe('On application start', () => {
    // Since the stepper is separate from the screen itself, it doesn't matter which screen we join
    const stepsWithExpectedErrors = ['start', 'authors']
    it('should have errors in start and authors, but not in any other steps', () => {
        cy.visit('/identifiers')
        stepsWithExpectedErrors.forEach((step) => {
            cy.checkThatStepperValidityIs(false, step)
        })
        // Future proofing, in case more steps add considered basic
        allStepNames.filter(x => !stepsWithExpectedErrors.includes(x))
            .forEach((step) => {
                cy.checkThatStepperValidityIs(true, step)
            })
    })
    it('should have error on preview', () => {
        cy.visit('/start')
        cy.dataCy('ta-cff-preview')
            .should('have.class', 'error')
        cy.dataCy('text-validation-msg')
            .should('have.class', 'invalid')
            .should('contain.text', 'minimum')
    })
})

describe('From a fixed advanced app', () => {
    beforeEach(() => {
        cy.visit('/start')
        cy.dataCy('input-title')
            .type('A')
        cy.visit('/authors')
        cy.dataCy('btn-add-author')
            .click()
        cy.visit('/identifiers')
    })
    it('should have no errors', () => {
        allStepNames.forEach((step) => {
            cy.checkThatStepperValidityIs(true, step)
            cy.dataCy('ta-cff-preview')
                .should('not.have.class', 'error')
            cy.dataCy('text-validation-msg')
                .should('not.have.class', 'invalid')
                .should('contain.text', 'Your CITATION.cff is valid')
        })
    })
    it('should validate screen Start', () => {
        cy.visit('/start')
        cy.dataCy('input-title')
            .clear()
        cy.checkThatStepperValidityIs(false, 'start')
        cy.dataCy('ta-cff-preview')
            .should('have.class', 'error')
        cy.dataCy('text-validation-msg')
            .should('have.class', 'invalid')
            .should('contain.text', 'minimum')
        cy.checkThatInputValidityIs(false, 'title')
        cy.get('.q-field__messages > div')
            .should('have.length', 1)

        cy.dataCy('input-message')
            .clear()
        cy.checkThatInputValidityIs(false, 'message')
        cy.get('.q-field__messages > div')
            .should('have.length', 2)

        cy.dataCy('input-title')
            .type('A')
        cy.findInputError('title')
            .should('not.exist')

        cy.checkThatStepperValidityIs(false, 'start')
        cy.dataCy('ta-cff-preview')
            .should('have.class', 'error')
        cy.dataCy('text-validation-msg')
            .should('have.class', 'invalid')
            .should('contain.text', 'minimum')

        cy.dataCy('input-message')
            .type('A')
        cy.checkThatInputValidityIs(true, 'message')
        cy.checkThatStepperValidityIs(true, 'start')
        cy.dataCy('ta-cff-preview')
            .should('not.have.class', 'error')
        cy.dataCy('text-validation-msg')
            .should('not.have.class', 'invalid')
            .should('contain.text', 'Your CITATION.cff is valid')
    })

    describe('On screen Authors', () => {
        beforeEach(() => {
            cy.visit('/authors')
        })

        it('should validate missing authors', () => {
            cy.dataCy('btn-remove')
                .click()
            cy.checkThatStepperValidityIs(false, 'authors')
            cy.dataCy('ta-cff-preview')
                .should('have.class', 'error')
            cy.dataCy('text-validation-msg')
                .should('have.class', 'invalid')
                .should('contain.text', 'minimum')
            cy.get('.q-banner')
                .should('contain.text', 'Use the button to add an author')
            cy.dataCy('btn-add-author')
                .click()
            cy.checkThatStepperValidityIs(true, 'authors')
            cy.dataCy('ta-cff-preview')
                .should('not.have.class', 'error')
            cy.dataCy('text-validation-msg')
                .should('not.have.class', 'invalid')
                .should('contain.text', 'Your CITATION.cff is valid')
        })
        it('should validate duplicate authors', () => {
            cy.dataCy('btn-remove')
                .click()
            cy.dataCy('btn-add-author')
                .click()
            cy.dataCy('input-given-names')
                .type('A')
            cy.dataCy('btn-done')
                .click()
            cy.dataCy('btn-add-author')
                .click()
            cy.dataCy('input-given-names')
                .type('A')
            cy.dataCy('btn-done')
                .click()

            cy.dataCy('card-author0')
                .should('have.class', 'has-error')
            cy.checkThatStepperValidityIs(false, 'authors')
            cy.dataCy('ta-cff-preview')
                .should('have.class', 'error')
            cy.dataCy('text-validation-msg')
                .should('have.class', 'invalid')
                .should('contain.text', 'minimum')
            cy.get('.q-banner')
                .should('contain.text', 'There are duplicate authors')

            cy.dataCy('btn-remove0')
                .click()
            cy.checkThatStepperValidityIs(true, 'authors')
            cy.dataCy('ta-cff-preview')
                .should('not.have.class', 'error')
            cy.dataCy('text-validation-msg')
                .should('not.have.class', 'invalid')
                .should('contain.text', 'Your CITATION.cff is valid')
        })
        it('should validate authors\' fields', () => {
            cy.dataCy('btn-remove')
                .click()
            cy.dataCy('btn-add-author')
                .click()
            cy.dataCy('input-email')
                .type('a')
            cy.checkThatStepperValidityIs(false, 'authors')
            cy.checkThatInputValidityIs(false, 'email')
            cy.checkThatAppValidityIs(false)
            cy.dataCy('input-email')
                .type('@a.com')
            cy.checkThatStepperValidityIs(true, 'authors')
            cy.checkThatInputValidityIs(true, 'email')
            cy.checkThatAppValidityIs(true)

            cy.dataCy('input-orcid')
                .type('1')
            cy.checkThatStepperValidityIs(false, 'authors')
            cy.checkThatInputValidityIs(false, 'orcid')
            cy.checkThatAppValidityIs(false)
            cy.dataCy('input-orcid')
                .type('23412341234123X')
                .parents('.q-field')
                .should('not.have.class', 'has-error')
            cy.checkThatStepperValidityIs(true, 'authors')
            cy.checkThatAppValidityIs(true)
        })
    })

    describe('On screen Identifiers', () => {
        beforeEach(() => {
            cy.visit('/identifiers')
        })
        it('should validate value', () => {
            cy.dataCy('btn-add-identifier')
                .click()
            cy.checkThatStepperValidityIs(false, 'identifiers')
            cy.checkThatInputValidityIs(false, 'value')
            cy.checkThatAppValidityIs(false)
            cy.dataCy('input-value')
                .type('10.1234/x')
            cy.checkThatStepperValidityIs(true, 'identifiers')
            cy.checkThatInputValidityIs(true, 'value')
            cy.checkThatAppValidityIs(true)
            cy.dataCy('input-value')
                .clear()
                .type('bad')
            cy.checkThatStepperValidityIs(false, 'identifiers')
            cy.checkThatInputValidityIs(false, 'value')
            cy.checkThatAppValidityIs(false)

            cy.dataCy('radio-identifier')
                .children()
                .eq(1)
                .click()
            cy.checkThatStepperValidityIs(false, 'identifiers')
            cy.checkThatInputValidityIs(false, 'value')
            cy.checkThatAppValidityIs(false)
            cy.dataCy('input-value')
                .clear()
                .type('https://a')
            cy.checkThatStepperValidityIs(true, 'identifiers')
            cy.checkThatInputValidityIs(true, 'value')
            cy.checkThatAppValidityIs(true)
            cy.dataCy('input-value')
                .clear()
            cy.checkThatStepperValidityIs(false, 'identifiers')
            cy.checkThatInputValidityIs(false, 'value')
            cy.checkThatAppValidityIs(false)

            cy.dataCy('radio-identifier')
                .children()
                .eq(2)
                .click()
            cy.checkThatStepperValidityIs(false, 'identifiers')
            cy.checkThatInputValidityIs(false, 'value')
            cy.checkThatAppValidityIs(false)
            cy.dataCy('input-value')
                .clear()
                .type('swh:1:rev:0123456789abcdef0123456789abcdef01234567')
            cy.checkThatStepperValidityIs(true, 'identifiers')
            cy.checkThatInputValidityIs(true, 'value')
            cy.checkThatAppValidityIs(true)
        })

        it('should validate duplicate identifiers', () => {
            cy.dataCy('btn-add-identifier')
                .click()
            cy.dataCy('input-value')
                .type('10.1234/x')
            cy.dataCy('btn-done')
                .click()
            cy.dataCy('btn-add-identifier')
                .click()
            cy.dataCy('input-value')
                .type('10.1234/x')
            cy.dataCy('btn-done')
                .click()
            cy.dataCy('card-identifier0')
                .should('have.class', 'has-error')
            cy.get('.q-banner')
                .should('contain.text', 'There are duplicate identifier')
            cy.checkThatStepperValidityIs(false, 'identifiers')
            cy.checkThatAppValidityIs(false)
            cy.dataCy('btn-remove0')
                .click()
            cy.checkThatStepperValidityIs(true, 'identifiers')
            cy.checkThatAppValidityIs(true)
        })
    })

    it('should validate screen Related Resources', () => {
        const fields = ['repository-code', 'url', 'repository', 'repository-artifact']
        cy.visit('/related-resources')
        fields.forEach((field) => {
            cy.dataCy(`input-${field}`)
                .type('bad')
            cy.checkThatStepperValidityIs(false, 'related-resources')
            cy.checkThatInputValidityIs(false, field)
            cy.checkThatAppValidityIs(false)
            cy.dataCy(`input-${field}`)
                .clear()
                .type('https://a')
            cy.checkThatStepperValidityIs(true, 'related-resources')
            cy.checkThatInputValidityIs(true, field)
            cy.checkThatAppValidityIs(true)
            cy.dataCy(`input-${field}`)
                .type(' ')
            cy.checkThatStepperValidityIs(false, 'related-resources')
            cy.checkThatInputValidityIs(false, field)
            cy.checkThatAppValidityIs(false)
            cy.dataCy(`input-${field}`)
                .clear()
            cy.checkThatStepperValidityIs(true, 'related-resources')
            cy.checkThatInputValidityIs(true, field)
            cy.checkThatAppValidityIs(true)
        })
    })

    describe('On screen keywords', () => {
        beforeEach(() => {
            cy.visit('/keywords')
        })
        it('should validate empty keywords', () => {
            cy.dataCy('btn-add-keyword')
                .click()
            cy.checkThatInputValidityIs(false, 'keyword0')
            cy.checkThatStepperValidityIs(false, 'keywords')
            cy.checkThatAppValidityIs(false)
            cy.dataCy('input-keyword0')
                .type('a')
            cy.checkThatInputValidityIs(true, 'keyword0')
            cy.checkThatStepperValidityIs(true, 'keywords')
            cy.checkThatAppValidityIs(true)
        })
        it('should validate duplicate keywords', () => {
            cy.dataCy('btn-add-keyword')
                .click()
                .click()
            cy.checkThatInputValidityIs(false, 'keyword0')
            cy.checkThatInputValidityIs(false, 'keyword1')
            cy.get('.q-banner')
                .should('contain.text', 'There are duplicate keywords')
            cy.checkThatStepperValidityIs(false, 'keywords')
            cy.checkThatAppValidityIs(false)
            cy.dataCy('input-keyword0')
                .type('a')
            cy.dataCy('input-keyword1')
                .type('b')
            cy.checkThatInputValidityIs(true, 'keyword0')
            cy.checkThatInputValidityIs(true, 'keyword1')
            cy.checkThatStepperValidityIs(true, 'keywords')
            cy.checkThatAppValidityIs(true)
        })
    })

    it('should validate screen Version Specific', () => {
        cy.visit('/version-specific')
        cy.dataCy('input-date-released')
            .type('1')
        cy.checkThatInputValidityIs(false, 'date-released')
        cy.checkThatStepperValidityIs(false, 'version-specific')
        cy.checkThatAppValidityIs(false)
        cy.dataCy('input-date-released')
            .type('1111111')
            .parents('.q-field')
            .should('not.have.class', 'has-error')
        cy.checkThatStepperValidityIs(true, 'version-specific')
        cy.checkThatAppValidityIs(true)
    })
})
